"""Добавлены новые поля

Revision ID: 9c6fd3c517c2
Revises: e31beef93767
Create Date: 2025-03-26 10:22:39.781423

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9c6fd3c517c2'
down_revision = 'e31beef93767'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('title', sa.String(), nullable=False, comment='Название вакансии'))
    op.add_column('jobs', sa.Column('description', sa.String(), nullable=False, comment='Описание вакансии'))
    op.add_column('jobs', sa.Column('salary_from', sa.Numeric(precision=10, scale=2), nullable=False, comment='Зарплата от'))
    op.add_column('jobs', sa.Column('salary_to', sa.Numeric(precision=10, scale=2), nullable=False, comment='Зарплата до'))
    op.add_column('jobs', sa.Column('is_active', sa.Boolean(), nullable=False, comment='Активна ли вакансия'))
    op.add_column('jobs', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Дата создания записи'))
    op.add_column('responses', sa.Column('message', sa.String(), nullable=True, comment='Сопроводительное письмо'))
    op.alter_column('responses', 'id',
               existing_type=sa.INTEGER(),
               comment='Идентификатор записи',
               existing_comment='Идентификатор отклика',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               comment='Дата создания записи',
               existing_comment='Время создания записи',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               comment='Время создания записи',
               existing_comment='Дата создания записи',
               existing_nullable=False)
    op.alter_column('responses', 'id',
               existing_type=sa.INTEGER(),
               comment='Идентификатор отклика',
               existing_comment='Идентификатор записи',
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('responses', 'message')
    op.drop_column('jobs', 'created_at')
    op.drop_column('jobs', 'is_active')
    op.drop_column('jobs', 'salary_to')
    op.drop_column('jobs', 'salary_from')
    op.drop_column('jobs', 'description')
    op.drop_column('jobs', 'title')
    # ### end Alembic commands ###
