"""Добавление ограничей уникальности

Revision ID: 6d59d942164d
Revises: 9c6fd3c517c2
Create Date: 2025-04-07 21:50:08.177388

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "6d59d942164d"
down_revision = "9c6fd3c517c2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("user_id_job_id_uc", "responses", ["user_id", "job_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("user_id_job_id_uc", "responses", type_="unique")
    # ### end Alembic commands ###
